# ==========================================
# CAU HINH KET NOI MySQL / Navicat
# ==========================================

# URL ket noi MySQL (zappy_db la ten database)
spring.datasource.url=jdbc:mysql://localhost:3306/zappy_db?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=010101
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ==========================================
# HIBERNATE - TU DONG TAO/CAP NHAT BANG SQL
# ==========================================
# update = tu dong tao bang neu chua co, cap nhat neu co thay doi
spring.jpa.hibernate.ddl-auto=update
# In ra cau SQL duoc chay (de debug)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ==========================================
# SERVER
# ==========================================
server.port=8080
spring.application.name=zappy-backend

# ==========================================
# CLOUDINARY CONFIG
# ==========================================
cloudinary.cloud-name=YOUR_CLOUD_NAME_HERE
cloudinary.api-key=987242293694251
cloudinary.api-secret=w-n_3gzuyY_Ve_Bp01SLBNougaU
# ==========================================
# GMAIL SMTP CONFIG
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
# Set biến môi trường trên window hoặc nhập thẳng vào đây để chạy, username là cái địa chỉ mail bạn sài để gửi mã otp, mật khẩu thì là app apssword của cái mail đó.
# Set bằng cách sài lệnh setX MAIL_USERNAME '....' và lệnh setX MAIL_PASSWORD '....' trong cmd
# Tạo app password thì lên google vào đường link: https://myaccount.google.com/apppasswords
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


